
services:
  postgres:
    image: pgvector/pgvector:pg17-trixie
    container_name: perkasm-postgres
    environment:
      POSTGRES_DB: perkasm
      POSTGRES_USER: perkasm
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perkasm -d perkasm -h localhost"]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: